// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Accountings = { name: string, income_expenditure: number, price: number, registered_at: string, memo: string, };
